/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Enter IP adress": {                             "en": "Enter IP adress",                                 "de": "Drucker IP Addresse",                             "ru": "Введите IP-адрес",                                "pt": "Digite o endereço IP",                            "nl": "Voer het IP-adres in",                            "fr": "Entrez l'adresse IP",                             "it": "Inserisci l'indirizzo IP",                        "es": "Ingrese la dirección IP",                         "pl": "Wprowadź adres IP"},
    "Epson Adapter settings": {                      "en": "Epson Stylus PX830 Adapter settings",             "de": "Epson Stylus PX830 Adapter Einstellungen",        "ru": "Настройки адаптера Epson Stylus PX 830",          "pt": "Configurações do adaptador Epson Stylus PX 830",  "nl": "Epson Stylus PX 830 Adapterinstellingen",         "fr": "Paramètres de l'adaptateur Epson Stylus PX 830",  "it": "Impostazioni della scheda Epson Stylus PX 830",   "es": "Configuración del adaptador Epson Stylus PX 830", "pl": "Ustawienia adaptera Epson Stylus PX 830"},
    "IP": {                                          "en": "ip adress of printer",                            "de": "IP Adresse des Druckers",                         "ru": "ip-адрес принтера",                               "pt": "endereço ip da impressora",                       "nl": "ip-adres van de printer",                         "fr": "adresse IP de l'imprimante",                      "it": "indirizzo IP della stampante",                    "es": "dirección IP de la impresora",                    "pl": "adres ip drukarki"},
    "Port": {                                        "en": "Port number",                                     "de": "Port Nummer",                                     "ru": "Номер порта",                                     "pt": "Número da porta",                                 "nl": "Poortnummer",                                     "fr": "Numéro de port",                                  "it": "Numero di porta",                                 "es": "Número de puerto",                                "pl": "Numer portu"},
    "Printer settings": {                            "en": "Printer settings",                                "de": "Drucker Einstellungen",                           "ru": "Настройки принтера",                              "pt": "Configurações da impressora",                     "nl": "Printer instellingen",                            "fr": "Paramètres de l'imprimante",                      "it": "Impostazioni della stampante",                    "es": "Configuración de la impresora",                   "pl": "Ustawienia drukarki"},
    "Synchronization": {                             "en": "Synchronization",                                 "de": "Synchronisierung",                                "ru": "синхронизация",                                   "pt": "Sincronização",                                   "nl": "Synchronisatie",                                  "fr": "Synchronisation",                                 "it": "Sincronizzazione",                                "es": "Sincronización",                                  "pl": "Synchronizacja"},
    "default is 180": {                              "en": "if left empty '180' will be used",                "de": "ohne Eingabe wird '180' verwendet",               "ru": "если останется пустой «180», будет использоваться", "pt": "se deixado vazio, '180' será usado",              "nl": "indien dit wordt gelaten, wordt lege '180' gebruikt", "fr": "si laissé vide '180' sera utilisé",               "it": "se lasciato vuoto verrà usato '180'",             "es": "si se deja en blanco, se usará '180'",            "pl": "jeśli pozostanie puste, zostanie użyte '180'"},
    "normally no port setting is required": {        "en": "normally no port setting is required",            "de": "Die Eingabe der Portnummer ist nicht zwingend",   "ru": "обычно настройка порта не требуется",             "pt": "normalmente não é necessária nenhuma configuração de porta", "nl": "normaal is er geen poortinstelling vereist",      "fr": "Normalement, aucun paramètre de port n'est requis", "it": "normalmente non è richiesta alcuna impostazione della porta", "es": "normalmente no se requiere configuración de puerto", "pl": "zwykle nie jest wymagane ustawienie portu"},
};